name: Publish Blog to Netlify

on:
  push:
    branches:
      - master

jobs:
  publish-netlify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make gradlew executable
        run: chmod +x ./build/gradlewCustom
      - name: Build with Gradle
        env: # Or as an environment variable
         LICENSE_KEY: ${{secrets.LICENSE_KEY}}
        run: |
          cd ./build
          ./gradlewCustom --info --stacktrace
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.OXYGEN_XML_BLOG_NETLIFY }}
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_SITE_ID: oxygenxmlblog
          build_directory: site
