name: Publish Blog to Netlify

on:
  push:
    branches:
      - master

jobs:
  publish-netlify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make gradlew executable
        run: chmod +x ./build/gradlewCustom
      - name: Build with Gradle
        env: # Or as an environment variable
         LICENSE_KEY: ${{secrets.LICENSE_KEY}}
        run: |
          cd ./build
          ./gradlewCustom --info --stacktrace          
