name: Validate And Check For Completeness Blog

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make gradlew executable
        run: chmod +x ./build/gradlewCustom
      - name: Build with Gradle
        env: # Or as an environment variable
         SCRIPTING_LICENSE_KEY: ${{secrets.SCRIPTING_LICENSE_KEY}}
        run: |
          cd ./build
          ./gradlewCustom --info --stacktrace runValidation
          if test -f ../validationReport.xml; then cat ../validationReport.xml > $GITHUB_STEP_SUMMARY;exit 1; fi
